### ISSUE TITLE
Allow filtering with "or" condition

### ISSUE THREAD

**Issue by LIQRGV** [LIQRGV/query-filter-laravel#3]
We should able transform this query param:
`x_model?filter[x|y][is]=1&filter[z][in]=1,2,3`

into this filter 
```
...... where (x = 1 or y = 1) and z in (1,2,3);
```

**Comment by PMessinezis** [comment]
I would like to give it a try. I am thinking of the following approach : 

1. in the constructor of FilterStruct :  check if  `"|"` is included in the fieldName, and if yes, then explode it into an array

2. in `apply()` method of FilterStruct :  if fieldName is an array, then create a $subquery closure applying  where/orWhere for the first and subsequent items in the fieldName array and then return `$object->where($subquery)`
