### ISSUE TITLE
Allow Model Setter

### ISSUE THREAD

**Issue by nafiesl** [LIQRGV/query-filter-laravel#9]
Hi @LIQRGV, I see this `RequestParser` class is guessing the model name by the current controller name. I think we need to allow user to set the model name with something like `setModel` method. let's say we have an `App\User` model, then in our controller:
```
public function index(RequestParser $parser)
{
    $builder = $parser->setModel(User::class)->getBuilder();
    // do something with builder
}
```
If you agree, I can prepare a PR for this feature.

Thanks.

**Comment by LIQRGV** [comment]
That would be cool,
also if it possible please refactor the "guessing" mechanism, make it optional if the model isn't set.

**Comment by nafiesl** [comment]
Got it @LIQRGV.
